const { jsPDF } = require("jspdf");

const MARGIN = 18;
const PAGE_WIDTH = 210; // A4, mm
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// Both of these already exist in controllers/formSchemaController.js, but
// this file isn't allowed to require that module: submitResponse (in that
// controller) needs to call buildReceiptPdfBuffer, and a require() back the
// other way would make the two files circularly dependent on each other —
// whichever loads first would see an incomplete module.exports from the
// other. A small duplicated copy of two pure functions is worth avoiding
// that. Also mirrors client/src/utils/formFieldDisplay.js on the frontend
// side, for the same "different JS environments" reason.
function formatFieldValue(field, value) {
  if (value === undefined || value === null || value === "") return "—";
  if (field.type === "checkbox") return value ? "Yes" : "No";
  if (field.type === "select") {
    const opt = field.options?.find((o) => o.value === value);
    return opt?.label ?? String(value);
  }
  return String(value);
}

function resolveVisibility(fields, values) {
  const byId = Object.fromEntries(fields.map((f) => [f.id, f]));
  const cache = new Map();

  function isVisible(field, seen = new Set()) {
    if (cache.has(field.id)) return cache.get(field.id);
    if (!field.showIf) {
      cache.set(field.id, true);
      return true;
    }
    if (seen.has(field.id)) return false;

    const parent = byId[field.showIf.field];
    if (!parent) {
      cache.set(field.id, true);
      return true;
    }
    const parentVisible = isVisible(parent, new Set(seen).add(field.id));
    const result = parentVisible && values[field.showIf.field] === field.showIf.equals;
    cache.set(field.id, result);
    return result;
  }

  return Object.fromEntries(fields.map((f) => [f.id, isVisible(f)]));
}

// Same layout as the client-side receipt (generateReceiptPdf.js) — this one
// exists purely so the confirmation email can attach a PDF without the
// submitter having to click "Download" first. jsPDF runs fine outside a
// browser; `.output("arraybuffer")` is all Node-specific about this.
function buildReceiptPdfBuffer({ schema, values, responseId, submittedAt }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(13, 148, 136);
  doc.text("Forma AI", MARGIN, y);
  y += 10;

  doc.setTextColor(20, 20, 43);
  doc.setFontSize(14);
  doc.text(`${schema.title} — Submission Receipt`, MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(98, 106, 133);
  doc.text(`Reference: ${responseId}`, MARGIN, y);
  y += 5;
  doc.text(`Submitted: ${new Date(submittedAt).toLocaleString()}`, MARGIN, y);
  y += 10;

  doc.setDrawColor(225, 227, 235);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  const visibility = resolveVisibility(schema.fields, values);
  const visibleFields = schema.fields.filter((f) => visibility[f.id]);

  for (const field of visibleFields) {
    if (y > 275) {
      doc.addPage();
      y = MARGIN;
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(98, 106, 133);
    doc.text(field.label, MARGIN, y);
    y += 5.5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(20, 20, 43);
    const valueText = formatFieldValue(field, values[field.id]);
    const lines = doc.splitTextToSize(valueText, CONTENT_WIDTH);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5.5 + 4;
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(160, 163, 180);
  doc.text("Generated by Forma AI — this is an automated receipt.", MARGIN, 287);

  return Buffer.from(doc.output("arraybuffer"));
}

module.exports = { buildReceiptPdfBuffer };
