import { jsPDF } from "jspdf";
import { formatFieldValue, resolveVisibility } from "./formFieldDisplay";

const MARGIN = 18;
const PAGE_WIDTH = 210; // A4, mm
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// Builds and downloads a one-page PDF receipt for a just-submitted response
// — same field list/formatting as the review screen, so what someone
// confirmed is exactly what the receipt shows. Client-side (jsPDF) rather
// than a backend endpoint: no new server dependency, and the browser
// already has everything it needs the instant submission succeeds.
export function generateReceiptPdf({ schema, values, responseId, submittedAt }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(13, 148, 136); // matches --accent
  doc.text("Forma AI", MARGIN, y);
  y += 10;

  doc.setTextColor(20, 20, 43);
  doc.setFontSize(14);
  doc.text(`${schema.title} — Submission Receipt`, MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(98, 106, 133);
  doc.text(`Reference: ${responseId}`, MARGIN, y);
  y += 5;
  doc.text(`Submitted: ${new Date(submittedAt).toLocaleString()}`, MARGIN, y);
  y += 10;

  doc.setDrawColor(225, 227, 235);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  const visibility = resolveVisibility(schema.fields, values);
  const visibleFields = schema.fields.filter((f) => visibility[f.id]);

  for (const field of visibleFields) {
    if (y > 275) {
      doc.addPage();
      y = MARGIN;
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(98, 106, 133);
    doc.text(field.label, MARGIN, y);
    y += 5.5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(20, 20, 43);
    const valueText = formatFieldValue(field, values[field.id]);
    const lines = doc.splitTextToSize(valueText, CONTENT_WIDTH);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5.5 + 4;
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(160, 163, 180);
  doc.text("Generated by Forma AI — this is an automated receipt.", MARGIN, 287);

  doc.save(`${schema.formId}-${responseId}.pdf`);
}
